version : "3.4"

services :
  sql-server :
    environment :
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports :
      - "5433:1433"
    volumes :
      - horcup-sql-server:/var/opt/mssql

  eventstore.db :
    environment :
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports :
      - "1113:1113"
      - "2113:2113"
    volumes :
      - type : volume
        source : horcup-volume-data
        target : /var/lib/eventstore
      - type : volume
        source : horcup-volume-logs
        target : /var/log/eventstore
        
#  rabbitmq :
#    ports :
#      - "15672:15672"
#      - "5672:5672"

  mongodb :
    ports :
      - "27017:27017"
    volumes :
      - horcup-mongodbdata:/var/opt/mongodb

  elasticsearch:
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - horcup-elasticsearchdata:/var/opt/elasticsearch

volumes :
  horcup-sql-server :
    driver : local

  horcup-mongodbdata :
    driver : local
    
  horcup-elasticsearchdata :
    driver : local

  horcup-volume-data :
    driver : local
    
  horcup-volume-logs :
    driver : local