version : "3.4"

services :
  sql-server :
    environment :
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports :
      - "5433:1433"
    volumes :
      - horcup-sql-server:/var/opt/mssql

  rabbitmq :
    ports :
      - "15672:15672"
      - "5672:5672"

  mongodb :
    ports :
      - "27017:27017"
    volumes :
      - horcup-mongodbdata:/var/opt/mongodb

  elasticsearch :
    ports :
      - "9200:9200"
      - "9300:9300"
    environment :
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes :
      - horcup-elasticsearchdata:/var/opt/elasticsearch

volumes :
  horcup-sql-server :
    driver : local

  horcup-mongodbdata :
    driver : local

  horcup-elasticsearchdata :
    driver : local